### ISSUE TITLE
Normalize the database schema across crawls

### ISSUE THREAD

**Issue by englehardt** [citp/openwpm-data-release#10]
We should be able to normalize the schema across crawls. We've mostly just added to the schema over time, so changes new columns can be added to old crawls and set to `null`. For breaking changes (like the change from `top_url` to `visit_id`, see #7), we may be able to re-write the old databases.

We can use the data generated from #9 to help with this process.

**Comment by gunesacar** [comment]
We add missing columns to databases with older schemas: https://github.com/citp/openwpm-data-release/blob/8723da57ae5a6b0a6c56e444d188249d383af187/normalize_db.py#L71

This is also where we add `visit_id` column to older tables with `top_url` and `page_url` columns.
