### ISSUE TITLE
2017 and 2018 crawls use a static top 1 million site list

### ISSUE THREAD

**Issue by englehardt** [citp/openwpm-data-release#13]
All crawls from 2017 and into the start of 2018 use a static site list from 2016-11-11 (specifically: https://webtransparency.cs.princeton.edu/misc/top-1m-11-11-2016.csv) 

See:
```
ab1b84debfdf67e2df358d2c7f04d0ba102b4e4143a1ed971067d39177d55b44  2015-12_1m_stateless-top-1m.csv
f43abdd4cb2595779d96ab060a094c0a13e1d98c75cb6de2077b1ff0fa7136f5  2016-03_1m_stateless-top-1m.csv
8fa16478d1d7d9206ec566e77ee46109dda66a44a5fd91ce9f86d0a2c6b788f8  2016-04_1m_stateless-top-1m.csv
e5112b2bd745d5d038b56499c9e96132e79827b79dbe102188e09f5ecf3676db  2016-05_1m_stateless-top-1m.csv
256eef5dd12513593c924ec4bc60bb3664956da365bcb9e8c9404a066cb54e49  2016-06_1m_stateless-top-1m.csv
77d2fe0d17c21adb80788cbe3ea65982b6ff6695d839878c2dd2797cf7d9e47a  2016-07_1m_stateless-top-1m.csv
c6ab995c6a14b83e231cffad8f8c73ae67134543e4cc36fd027129003e694487  2016-08_1m_stateless-top-1m.csv
83bc0c606c72e1183e93a75ee783afa2f150c301512743e317a6a90e51be3899  2016-09_1m_stateless-top-1m.csv
ddc0ab54531d9c4a89594b76aad18656ead0249ce354da533b91f9873ec02f60  2017-01_1m_stateless-top-1m.csv
ddc0ab54531d9c4a89594b76aad18656ead0249ce354da533b91f9873ec02f60  2017-02_1m_stateless-top-1m.csv
ddc0ab54531d9c4a89594b76aad18656ead0249ce354da533b91f9873ec02f60  2017-03_1m_stateless-top-1m.csv
ddc0ab54531d9c4a89594b76aad18656ead0249ce354da533b91f9873ec02f60  2017-04_1m_stateless-top-1m.csv
ddc0ab54531d9c4a89594b76aad18656ead0249ce354da533b91f9873ec02f60  2017-05_1m_stateless-top-1m.csv
ddc0ab54531d9c4a89594b76aad18656ead0249ce354da533b91f9873ec02f60  2017-06_1m_stateless-top-1m.csv
ddc0ab54531d9c4a89594b76aad18656ead0249ce354da533b91f9873ec02f60  2017-07_1m_stateless-top-1m.csv
ddc0ab54531d9c4a89594b76aad18656ead0249ce354da533b91f9873ec02f60  2017-09_1m_stateless-top-1m.csv
ddc0ab54531d9c4a89594b76aad18656ead0249ce354da533b91f9873ec02f60  2017-10_1m_stateless-top-1m.csv
ddc0ab54531d9c4a89594b76aad18656ead0249ce354da533b91f9873ec02f60  2017-12_1m_stateless-top-1m.csv
ddc0ab54531d9c4a89594b76aad18656ead0249ce354da533b91f9873ec02f60  2018-01_1m_stateless-top-1m.csv
ddc0ab54531d9c4a89594b76aad18656ead0249ce354da533b91f9873ec02f60  2018-02_1m_stateless-top-1m.csv
```

**Comment by englehardt** [comment]
To address this in the data release we've decided to do the following:
* Use [this archive]() of the Alexa top 1 million list to retrieve the appropriate list for the start of the crawl.
* Populate the `alexa_rank` column based on those lists. For entries that aren't on the archive list, enter `null`.
* Include a extra column `2016_11_alexa_rank` that includes all the rank information from the list used for the crawl.

This makes it explicit that the rank information is incomplete and that outdated info is available.

**Comment by randomwalker** [comment]
This approach sounds good. Don't sweat it too much. In general, we should be totally open about the fact that there might be incompleteness and other messiness in our data; the guarantee that we're providing is not that our data is perfect, but that we've documented all known issues to the best of our accuracy and provided ways for users of the data to recover from those issues to the extent possible.

**Comment by gunesacar** [comment]
I implemented this fix. The data is being reprocessed.
Instead of `2016_11_alexa_rank` I used `crawled_alexa_rank` as the column name, since we didn't use `2016_11` ranks in the pre-2017 crawls.

**Comment by gunesacar** [comment]
The number of visits with NULL Alexa ranks (sites that are not included in the Alexa top 1M list of the crawl date) range from 276K to 596K.

2017-01_1m_stateless 276111
2017-02_1m_stateless 287512
2017-03_1m_stateless 300962
2017-04_1m_stateless 326824
2017-05_1m_stateless 338552
2017-06_1m_stateless 329021
2017-07_1m_stateless 369154
2017-09_1m_stateless 387522
2017-10_1m_stateless 392604
2017-12_1m_stateless 420449
2018-01_1m_stateless 437534
2018-02_1m_stateless 596181
2018-03_1m_stateless 580725
2018-06_1m_stateless 603971
