### ISSUE TITLE
Invalid definition of `javascript_view` in `schema.sql` from webcensus site

### ISSUE THREAD

**Issue by birdsarah** [citp/openwpm-data-release#16]
Hi!

Apologies if this is the wrong place for this comment, I wasn't sure where the best place would be.

I downloaded `schema.sql` from https://webtransparency.cs.princeton.edu/webcensus/data/schema.sql via the link at https://webtransparency.cs.princeton.edu/webcensus/#data

This schema does not run as provided:

Specifically, lines 343 - 364 read:

```sql
CREATE OR REPLACE VIEW
    javascript_view (id, top_url, script_url, script_line, script_col,
                     call_stack, symbol, value, pindex, pvalue) AS
    SELECT j.id, sv.top_url, u.url, j.script_line, j.script_col, j.call_stack,
           s.symbol, v.value, p.pindex, p.pvalue
    FROM
        javascript AS j
        LEFT JOIN
            javascript_values as v
            ON v.id = j.value_id
        LEFT JOIN
            javascript_symbols as s
            ON s.id = j.symbol_id
        LEFT JOIN
            javascript_parameters as p
            ON p.id = j.parameter_id
        LEFT JOIN
            site_visits as sv
            ON sv.id = j.visit_id
        LEFT JOIN
            urls as u
            ON u.id = j.url_id;
```

but script_line, script_col, and call_stack are not available in the `javascript` table as defined by this schema L145 - 153:

```sql
CREATE TABLE IF NOT EXISTS javascript (
    id INTEGER PRIMARY KEY,
    visit_id INTEGER NOT NULL,
    url_id INTEGER,
    symbol_id INTEGER NOT NULL,
    operation TEXT NOT NULL,
    value_id INTEGER,
    parameter_id INTEGER
);
```

Simply altering L343-364 to remove the references to the missing columns was sufficient for everything to run:

```sql
CREATE OR REPLACE VIEW
    javascript_view (id, top_url, script_url, symbol, value, pindex, pvalue) AS
    SELECT j.id, sv.top_url, u.url, s.symbol, v.value, p.pindex, p.pvalue
    FROM
        javascript AS j
        LEFT JOIN
```

**Comment by birdsarah** [comment]
I notice that those columns are available in the db schema mentioned in this repo.

**Comment by gunesacar** [comment]
Thanks for reporting!

(let me page @englehardt, since he may know the context better.)

`script_line, script_col, and call_stack` are added in May 2016. So the schema.sql you mention may not be compatible with older crawl data.

As part of this release, we have normalized DB schemas, i.e. all databases will have the same structure. Hopefully this will help with the issue.

**Comment by englehardt** [comment]
I've updated the schema file to remove the extra columns. What likely happened here was that we released the dataset around May 2016, and I must have copied the view building SQL from a newer version of the schema. Thanks for the fix!
