### ISSUE TITLE
Build a timeline of important changes

### ISSUE THREAD

**Issue by gunesacar** [citp/openwpm-data-release#4]
Let's publish a changelog along with the dataset. This should include important architectural changes like switching to extension-based HTTP monitoring, changes in the database scheme etc.

**Comment by englehardt** [comment]
* May 2016 -- Command sequence / site_visits / visit_id [first added](https://github.com/citp/OpenWPM/pull/74).
* December 2016 -- HTTP extension-based instrumentation [first added](https://github.com/citp/OpenWPM/commit/5d86590149a6eae9d805076ab0543c959dac7df2#diff-046afae7a86bd3a4aaa90104f3b3d18e)
